banking/urls.py
from django.urls import path

from . import views

app_name = 'banking'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('profile/', views.profile, name='profile'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    
]

palmsbank/urls.py
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('banking.urls', namespace="banking")),
    path('accounts/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT )
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )

banking/models.py
from django.db import models

# Create your models here.

banking/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'banking/home.html')

def login(request):
    return render(request, 'banking/login.html')

def profile(request):
    return render(request, 'registration/profile.html')

def contact(request):
    return render(request, 'banking/contact.html')

def about(request):
    return render(request, 'banking/about.html')

banking/templates/banking/about.html
{% extends 'banking/base.html' %} {% load static %} {% block title %} Palms Bank
- About Us {% endblock title %} {% block content %}
<section class="about" style="margin-top: 200px">
  <div class="container">
    <div class="row justify-content-center mb-4">
      <h3><span class="bigger">A</span>bout Us</h3>
    </div>
    <div class="row">
      <div class="col-12 col-md-6">
        <img src="{% static 'images/bg3.jpg' %}" alt="" width="100%" />
      </div>
      <div class="col-12 col-md-6">
        <div class="row">
          <h4>
            We Recognize That Our People, Our Culture, And Our Customers
            Contribute Equal Parts To Our Success.
          </h4>
        </div>
        <div class="row mt-5">
          <p class="font-weight-bolder">Our People</p>
          <p>
            Our people are our greatest asset. We are committed to developing
            and growing employees at all levels in order to drive business
            results. We use our Performance Management and Talent Management
            practices to allow us to identify future leaders and prepare them
            for challenging roles. These practices include succession planning,
            extensive learning and development opportunities, robust feedback
            processes, and ongoing engagement by managers at all levels. We want
            to ensure we have the best people in every role.
          </p>
        </div>
        <div class="row mt-5">
          <p class="font-weight-bolder">Our Culture</p>
          <p>
            At the heart of our success is the Metro finance® culture. We
            provide our associates with a dynamic environment combined with two
            key values: Excellence and Do the Right Thing. We take pride in
            encouraging our associates to think independently in a collaborative
            setting and to present creative ideas to senior management. It's
            this type of innovative thinking that is a major part of our
            corporate growth as well as the overall success ofWema Trust Union
            Bank.
          </p>
        </div>
      </div>
    </div>
  </div>
</section>
<section>
  <div class="about-bg container-fluid text-light">
    <div class="container">
      <div class="row justify-content-center mt-4">
        <h3 class="mt-5"><span class="bigger">C</span>ustomers Feedback</h3>
      </div>
      <div class="row justify-content-center">
        <div class="col-md-4 col-12">
          <div class="card">
            <img
              class="card-img-top"
              src="{% static 'images/profile1.jpg' %}"
              alt=""
            />
            <div class="card-body">
              <h4 class="card-title">Laura Paul</h4>
              <p class="card-text">
                Good Day, My name is Laura i am a citizen of the United State of
                America i want to testify of the good Loan Lender(United Nations
                Insurance Bank) who showed light to me after been scammed by 4
                different Internet international lender
              </p>
            </div>
          </div>
        </div>
        <div class="col-md-4 col-12">
          <div class="card">
            <img
              class="card-img-top"
              src="{% static 'images/profile2.jpg' %}"
              alt=""
            />
            <div class="card-body">
              <h4 class="card-title">Rosy Crips</h4>
              <p class="card-text">
                I would have saved so much time and money if only I knew of my
                housing loan sooner. Well done!
              </p>
            </div>
          </div>
        </div>
        <div class="col-md-4 col-12">
          <div class="card">
            <img
              class="card-img-top"
              src="{% static 'images/profile3.jpg' %}"
              alt=""
            />
            <div class="card-body">
              <h4 class="card-title">Christiana lewis</h4>
              <p class="card-text">
                My name are Michael Ryan ,i am here to testify how i got my
                mortgage fromWema Trust Union Bank after i applied several times
                for various mortgage lenders. I was in need of an urgent
                mortgage to start a business and i applied from various mortgage
                lenders who promised to help but they never gave me the
                mortgage.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<main>
  <div class="container mt-5">
    <div class="row py-2 mt-5">
      <div class="row py-2 text-start mt-5">
        <div class="col-md-3">
          <p>
            <img src="/static/images/icon/5.ico" alt="" width="10%" /><span
              class="font-weight-bolder"
            >
              Mobile Apps</span
            >
          </p>
          <p>
            Make your life experiences simpler and stay in control with Mobile
            Banking app. manage your finances; make card settlementS & transfer
            funds
          </p>
        </div>
        <div class="col-md-3">
          <p>
            <img src="/static/images/icon/6.ico" alt="" width="10%" /><span
              class="font-weight-bolder"
            >
              Security Tips</span
            >
          </p>
          <p>
            Easy to use and secure. Manage borrowers, loans, repayments, and
            reports. Software developed for cash lending industry. Manage
            borrowers, loans, repayments, reports.
          </p>
        </div>
        <div class="col-md-3">
          <p>
            <img src="/static/images/icon/7.ico" alt="" width="10%" /><span
              class="font-weight-bolder"
            >
              Various Branches</span
            >
          </p>
          <p>
            Credit cards offer exceptional benefits, rewards, services and
            spending power that can help make your financial and personal dreams
            come true.
          </p>
        </div>
        <div class="col-md-3">
          <p>
            <img src="/static/images/icon/8.ico" alt="" width="10%" /><span
              class="font-weight-bolder"
            >
              24/7 Support</span
            >
          </p>
          <p>
            access more. Customer Support. Our multi-lingual Contact Center is a
            world-class customer interaction center which offers you 24/7, real
            time information.
          </p>
        </div>
      </div>
    </div>
  </div>
  <!--Zoom effect-->
</main>
{% endblock content %}

banking/templates/banking/base.html
<!DOCTYPE html>
<html lang="en">
{% include 'banking/head.html' %}

<body>
  {% include 'banking/nav.html' %} {% block content %} {% endblock content %}
  {% include 'banking/footer.html' %} {% include 'banking/scripts.html' %}
</body>

</html>

banking/templates/banking/contact.html
{% extends 'banking/base.html' %}
{% block title %}
Palms Bank- Contact Us
{%endblock title %}
{% block content %}
<!--Section: Contact v.2-->
<section class="my-5">
  <div class="row justify-content-center">
    <div class="card w-75">
      <div class="card-body">
        <!--Section heading-->
        <h2 class="h1-responsive font-weight-bold text-center my-4">
          Contact us
        </h2>
        <hr class="text-muted" />
        <!--Section description-->
        <p class="text-center w-responsive mx-auto mb-5">
          Do you have any questions? Please do not hesitate to contact us
          directly. Our team will come back to you within a matter of hours to
          help you.
        </p>
        <div class="row">
          <!--Grid column-->
          <div class="col-md-9 mb-md-0 mb-5">
            <form id="contact-form" name="contact-form" action="." method="POST">
              {% csrf_token %}
              <!--Grid row-->
              <div class="row">
                <!--Grid column-->
                <div class="col-md-6">
                  <div class="md-form mb-0">
                    <input type="text" id="name" name="name" class="form-control" />
                    <label for="name" class="">Your name</label>
                  </div>
                </div>
                <!--Grid column-->
                <!--Grid column-->
                <div class="col-md-6">
                  <div class="md-form mb-0">
                    <input type="text" id="email" name="email" class="form-control" />
                    <label for="email" class="">Your email</label>
                  </div>
                </div>
                <!--Grid column-->
              </div>
              <!--Grid row-->
              <!--Grid row-->
              <div class="row">
                <div class="col-md-12">
                  <div class="md-form mb-0">
                    <input type="text" id="subject" name="subject" class="form-control" />
                    <label for="subject" class="">Subject</label>
                  </div>
                </div>
              </div>
              <!--Grid row-->
              <!--Grid row-->
              <div class="row">
                <!--Grid column-->
                <div class="col-md-12">
                  <div class="md-form">
                    <textarea type="text" id="message" name="message" rows="2"
                      class="form-control md-textarea"></textarea>
                    <label for="message">Your message</label>
                  </div>
                </div>
              </div>
              <!--Grid row-->
            </form>
            <div class="text-center text-md-left">
              <a class="btn btn-primary" onclick="document.getElementById('contact-form').submit();">Send</a>
            </div>
            <div class="status"></div>
          </div>
          <!--Grid column-->
          <!--Grid column-->
          <div class="col-md-3 text-center">
            <ul class="list-unstyled mb-0">
              <li>
                <i class="fas fa-map-marker-alt fa-2x"></i>
                <p>New York, NY 10012, US</p>
              </li>
              <li>
                <i class="fas fa-phone mt-4 fa-2x"></i>
                <p>+ 01 234 567 88</p>
              </li>
              <li>
                <i class="fas fa-envelope mt-4 fa-2x"></i>
                <p>info@example.com</p>
              </li>
            </ul>
          </div>
          <!--Grid column-->
        </div>
      </div>
    </div>
  </div>
</section>
<!--Section: Contact v.2-->
{% endblock content %}

banking/templates/banking/footer.html
<footer
  class="page-footer font-small unique-color-danger text-light"
  style="background-color: black"
>
  <div style="background-color: #6351ce">
    <div class="container">
      <!-- Grid row-->
      <div class="row py-4 d-flex align-items-center">
        <!-- Grid column -->
        <div class="col-md-6 col-lg-5 text-center text-md-left mb-4 mb-md-0">
          <h6 class="mb-0">Get connected with us on social networks!</h6>
        </div>
        <!-- Grid column -->
        <!-- Grid column -->
        <div class="col-md-6 col-lg-7 text-center text-md-right">
          <!-- Facebook -->
          <a class="fb-ic">
            <i class="fab fa-facebook-f white-text mr-4"> </i>
          </a>
          <!-- Twitter -->
          <a class="tw-ic">
            <i class="fab fa-twitter white-text mr-4"> </i>
          </a>
          <!-- Google +-->
          <a class="gplus-ic">
            <i class="fab fa-google-plus-g white-text mr-4"> </i>
          </a>
          <!--Linkedin -->
          <a class="li-ic">
            <i class="fab fa-linkedin-in white-text mr-4"> </i>
          </a>
          <!--Instagram-->
          <a class="ins-ic">
            <i class="fab fa-instagram white-text"> </i>
          </a>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row-->
    </div>
  </div>
  <!-- Footer Links -->
  <div class="container text-center text-md-left mt-5">
    <!-- Grid row -->
    <div class="row mt-3">
      <!-- Grid column -->
      <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
        <!-- Content -->
        <img src="/static/images/icon/logo.ico" alt="" />
        <h6 class="text-uppercase font-weight-bold">Palms Bank</h6>
        <hr
          class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto"
          style="width: 60px"
        />
      </div>
      <!-- Grid column -->
      <!-- Grid column -->
      <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Products</h6>
        <hr
          class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto"
          style="width: 60px"
        />
        <p>
          <a href="#!">Online Banking</a>
        </p>
        <p>
          <a href="#!">Credit Cards</a>
        </p>
        <p>
          <a href="#!">Business Loans</a>
        </p>
        <p>
          <a href="#!">POS</a>
        </p>
      </div>
      <!-- Grid column -->
      <!-- Grid column -->
      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Useful links</h6>
        <hr
          class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto"
          style="width: 60px"
        />
        <p>
          <a href="#!">Your Account</a>
        </p>
        <p>
          <a href="#!">Become an Affiliate</a>
        </p>
        <p>
          <a href="#!">Career</a>
        </p>
        <p>
          <a href="#!">Help</a>
        </p>
      </div>
      <!-- Grid column -->
      <!-- Grid column -->
      <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Contact</h6>
        <hr
          class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto"
          style="width: 60px"
        />
        <p><i class="fas fa-home"></i> New York, NY 10012, US</p>
        <p><i class="fas fa-envelope mr-3"></i> info@example.com</p>
        <p><i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>
        <p><i class="fas fa-print mr-3"></i> + 01 234 567 89</p>
      </div>
      <!-- Grid column -->
    </div>
    <!-- Grid row -->
  </div>
  <!-- Footer Links -->
  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">
    © 2020 Copyright:
    <a href="/"
      ><img src="/static/images/icon/logo.ico" alt="" width="20px" />
      PalmsBank.com</a
    >
  </div>
  <!-- Copyright -->
</footer>

banking/templates/banking/head.html
{% load static %}
<head>
  <title>{% block title %} {% endblock title %}</title>
  <meta charset="utf-8" />
  <meta
    name="viewport"
    content="width=device-width, initial-scale=1, shrink-to-fit=no"
  />
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
    crossorigin="anonymous"
  />
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>

banking/templates/banking/header.html
<header>
  <!--Navbar-->
  <!-- Full Page Intro -->
  <div
    class="view"
    style="
      background-image: url(/static/images/bg.jpg);
      background-repeat: no-repeat;
      background-size: cover;
      background-position: center center;
      margin-top: 100px;
    "
  >
    <!-- Mask & flexbox options-->
    <div class="mask rgba-gradient align-items-center">
      <!-- Content -->
      <div class="container">
        <!--Grid row-->
        <div class="row">
          <!--Grid column-->
          <div
            class="
              col-md-6
              text-light text-center text-md-left
              mt-xl-5
              mb-5
              wow
              fadeInLeft
            "
            data-wow-delay="0.3s"
            style="margin-top: 100px"
          >
            <h1 class="h1-responsive font-weight-bold mt-sm-5">
              Business Loans <br />
              <span class="text-primary"> Cash management</span>
            </h1>
            <hr class="hr-light" />
            <h6 class="mb-4">
              Have an idea for your business? Need a loan to make it a reality?
              We offer loan options for a variety of business purposes. Our
              knowledgeable loan officers will review choices with you and help
              you determine the best fit for your business. We want to see your
              business grow and succeed!
            </h6>
            <a class="btn btn-primary">Read More</a>
            <a class="btn btn-outline-primary text-dark">Get Started</a>
          </div>
          <!--Grid column-->
          <!--Grid column-->
          <div
            class="col-md-6 col-xl-5 mt-xl-5 wow fadeInRight"
            data-wow-delay="5s"
          >
            <img
              src="https://mdbootstrap.com/img/Mockups/Transparent/Small/admin-new.png"
              alt=""
              class="img-fluid"
            />
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->
      </div>
      <!-- Content -->
    </div>
    <!-- Mask & flexbox options-->
  </div>
  <!-- Full Page Intro -->
</header>

banking/templates/banking/home.html
{% extends 'banking/base.html' %} {% load static %} {% block title %} Palms Bank
{% endblock title %} {% block content %}
<!-- Main navigation -->
<!--Main Layout-->
<header>
  <!--Navbar-->
  <!-- Full Page Intro -->
  <div
    class="view"
    style="
      background-image: url(/static/images/bg.jpg);
      background-repeat: no-repeat;
      background-size: cover;
      background-position: center center;
    "
  >
    <!-- Mask & flexbox options-->
    <div class="mask rgba-gradient align-items-center">
      <!-- Content -->
      <div class="container">
        <!--Grid row-->
        <div class="row">
          <!--Grid column-->
          <div
            class="
              col-md-6
              text-light text-center text-md-left
              mt-xl-5
              mb-5
              wow
              fadeInLeft
            "
            data-wow-delay="0.3s"
          >
            <h1 class="h1-responsive font-weight-bold mt-sm-5">
              Business Loans <br />
              <span class="text-primary"> Cash management</span>
            </h1>
            <hr class="hr-light" />
            <h6 class="mb-4">
              Have an idea for your business? Need a loan to make it a reality?
              We offer loan options for a variety of business purposes. Our
              knowledgeable loan officers will review choices with you and help
              you determine the best fit for your business. We want to see your
              business grow and succeed!
            </h6>
            {% if user.is_authenticated %}
            <a class="btn btn-primary">Read More</a>
            {% else %}
            <a class="btn btn-primary">Read More</a>
            <a class="btn btn-outline-primary text-dark" href="accounts/login"
              >Get Started</a
            >
            {% endif %}
          </div>
          <!--Grid column-->
          <!--Grid column-->
          <div
            class="col-md-6 col-xl-5 mt-xl-5 wow fadeInRight"
            data-wow-delay="5s"
          >
            <img
              src="https://mdbootstrap.com/img/Mockups/Transparent/Small/admin-new.png"
              alt=""
              class="img-fluid"
            />
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->
      </div>
      <!-- Content -->
    </div>
    <!-- Mask & flexbox options-->
  </div>
</header>
<main>
  <div class="container mt-5">
    <!--Grid row-->
    <div class="row">
      <!--Grid column-->
      <div class="col-md-4 text-center">
        <img src="/static/images/1.png" alt="" width="80%" height="40%" />
        <h3>Statitics</h3>
        <p>
          Chart Your Own Course, Select Your Own Investments And Analyze Your
          Own Portfolio—On Your Own, All Online. We're Just Here To Give You
          Tools To Help You Steer Your Own Financial Ship.
        </p>
      </div>
      <div class="col-md-4 text-center">
        <img src="/static/images/2.png" alt="" width="80%" height="40%" />
        <h3>Security</h3>
        <p>
          Our Financial Advisors Will Work With You To Build A Plan Tailored To
          Your Goals, And Offer Advice And Investing Products Intended To Help
          You Make Progress.
        </p>
      </div>
      <div class="col-md-4 text-center">
        <img src="/static/images/3.png" alt="" width="80%" height="40%" />
        <h3>Presentation</h3>
        <p>
          We Want To Make It As Straightforward As Possible For You To Pursue
          Your Goals. Use Our Intuitive Research And Investing Tools To Discover
          Investments And Build Your Online Portfolio. PortfolioBuilder.
        </p>
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->
  </div>
</main>
<main>
  <div
    class="view"
    style="
      background-image: url(/static/images/bg2.jpg);
      background-repeat: no-repeat;
      background-size: cover;
      background-position: center center;
    "
  >
    <!-- Mask & flexbox options-->
    <div class="mask rgba-gradient align-items-center">
      <!-- Content -->
      <div class="container">
        <!--Grid row-->
        <div class="row">
          <!--Grid column-->
          <div
            class="
              col-md-6
              text-light text-center text-md-left
              mt-xl-2
              mb-5
              wow
              fadeInLeft
            "
            data-wow-delay="0.3s"
          >
            <h1 class="h1-responsive font-weight-bold mt-sm-5">
              Business Loans <br />
              <span class="text-primary"> Cash management</span>
            </h1>
            <hr class="hr-light" />
            <h6 class="mb-4">
              Have an idea for your business? Need a loan to make it a reality?
              We offer loan options for a variety of business purposes. Our
              knowledgeable loan officers will review choices with you and help
              you determine the best fit for your business. We want to see your
              business grow and succeed!
            </h6>
            <!-- <a class="btn btn-dark">Read More</a>
                        <a class="btn btn-outline-dark text-dark">Get Started</a> -->
          </div>
          <!--Grid column-->
          <!--Grid column-->
          <div
            class="col-md-6 col-xl-5 mt-xl-5 wow fadeInRight"
            data-wow-delay="5s"
          >
            <img
              src="/static/images/5.png"
              alt=""
              class="img-fluid"
              width="100%"
              height="100%"
            />
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->
      </div>
      <!-- Content -->
    </div>
    <!-- Mask & flexbox options-->
  </div>
</main>
<main>
  <div class="container py-5">
    <div class="row py-2 justify-content-center">
      <h2 class="text-center">Products to Meet Your Life Goals</h2>
    </div>
    <div class="row py-5 text-center">
      <div class="col-md-3">
        <div class="card">
          <div class="card-body zoom">
            <div
              style="
                background: url(/static/images/icon/1.ico) no-repeat center;
                height: 100px;
                width: 100%;
              "
            ></div>
            <h6 class="card-title">Personal Loan</h6>
            <img src="/static/images/icon/arrow.ico" alt="" />
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card">
          <div class="card-body zoom">
            <div
              style="
                background: url(/static/images/icon/2.ico) no-repeat center;
                height: 100px;
                width: 100%;
              "
            ></div>
            <h6 class="card-title">Fixed Deposit</h6>
            <img src="/static/images/icon/arrow.ico" alt="" />
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card">
          <div class="card-body zoom">
            <div
              style="
                background: url(/static/images/icon/3.ico) no-repeat center;
                height: 100px;
                width: 100%;
              "
            ></div>
            <h6 class="card-title text-nowrap">Savings Account</h6>
            <img src="/static/images/icon/arrow.ico" alt="" />
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card">
          <div class="card-body zoom">
            <div
              style="
                background: url(/static/images/icon/4.ico) no-repeat center;
                height: 100px;
                width: 100%;
              "
            ></div>
            <h6 class="card-title">Credit Cards</h6>
            <img src="/static/images/icon/arrow.ico" alt="" />
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--Zoom effect-->
</main>
<main>
  <div class="container">
    <div class="row py-2">
      <div class="row py-2 text-start">
        <div class="col-md-3">
          <p>
            <img src="/static/images/icon/5.ico" alt="" width="10%" /><span
              class="font-weight-bolder"
            >
              Mobile Apps</span
            >
          </p>
          <p>
            Make your life experiences simpler and stay in control with Mobile
            Banking app. manage your finances; make card settlementS & transfer
            funds
          </p>
        </div>
        <div class="col-md-3">
          <p>
            <img src="/static/images/icon/6.ico" alt="" width="10%" /><span
              class="font-weight-bolder"
            >
              Security Tips</span
            >
          </p>
          <p>
            Easy to use and secure. Manage borrowers, loans, repayments, and
            reports. Software developed for cash lending industry. Manage
            borrowers, loans, repayments, reports.
          </p>
        </div>
        <div class="col-md-3">
          <p>
            <img src="/static/images/icon/7.ico" alt="" width="10%" /><span
              class="font-weight-bolder"
            >
              Various Branches</span
            >
          </p>
          <p>
            Credit cards offer exceptional benefits, rewards, services and
            spending power that can help make your financial and personal dreams
            come true.
          </p>
        </div>
        <div class="col-md-3">
          <p>
            <img src="/static/images/icon/8.ico" alt="" width="10%" /><span
              class="font-weight-bolder"
            >
              24/7 Support</span
            >
          </p>
          <p>
            access more. Customer Support. Our multi-lingual Contact Center is a
            world-class customer interaction center which offers you 24/7, real
            time information.
          </p>
        </div>
      </div>
    </div>
  </div>
  <!--Zoom effect-->
</main>
<!--Main Layout-->
<!-- Footer -->
<!-- Footer -->
{% endblock content %}

banking/templates/banking/nav.html
<nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar">
  <div class="container">
    <a class="navbar-brand" href="/">
      <img src="/static/images/icon/logo.ico" alt="" />
      <strong>Palms Bank</strong>
    </a>
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarSupportedContent-7"
      aria-controls="navbarSupportedContent-7"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent-7">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/"
            >HOME
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">SERVICES</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'banking:about' %}">ABOUT US</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'banking:contact' %}">CONTACT US</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link btn btn-danger ml-3" href="/accounts/logout"
            >LOG OUT</a
          >
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link btn btn-primary" href="/accounts/login"
            >ONLINE BANKING</a
          >
        </li>
        {% endif %}
      </ul>
      <!-- <form class="form-inline">
                    <div class="md-form my-0">
                        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                    </div>
                </form> -->
    </div>
  </div>
</nav>

banking/templates/banking/scripts.html
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
</script>